In [1]:
print("!! Jai Ganesh !!")

!! Jai Ganesh !!


In [2]:
import numpy as np

In [3]:
l=[1,2,3,4]

In [4]:
np.array(l)

array([1, 2, 3, 4])

In [5]:
l

[1, 2, 3, 4]

In [6]:
myarray=np.array(l)

In [8]:
myarray

array([1, 2, 3, 4])

In [7]:
type(myarray)

numpy.ndarray

In [9]:
mymatrix=[[1,2,3],[4,5,6],[7,8,9]]

In [10]:
np.array(mymatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.ones((4,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [25]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [27]:
len(np.linspace(0,5,21))

21

In [28]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
np.random.rand(1)

array([0.46812471])

In [32]:
np.random.rand(5,2)

array([[0.26609024, 0.23954032],
       [0.73587438, 0.52899362],
       [0.75679686, 0.43407731],
       [0.20070289, 0.19358673],
       [0.20988068, 0.2706803 ]])

In [41]:
a=np.random.randn(10)

In [42]:
a.max()

1.013988535126493

In [43]:
a.mean()

-0.04457135346513904

In [44]:
np.random.randn(5,3)

array([[-1.93932721,  0.32919485, -0.34093609],
       [-0.29714356,  1.30834163,  2.80905676],
       [-0.27347274, -1.06284894, -0.04345397],
       [-0.77162663, -0.95064876,  0.07369523],
       [-0.28641047,  0.22017651, -1.36506624]])

In [48]:
np.random.randint(0,101,50)

array([ 14,  35,  93,  88,  66,  74,   0,  74,  89,  64,  75,  27,  60,
        38,   9,  94,  42,  13,  55,  29, 100,   5,  61, 100,  44,  31,
        91,  68,  88,  18, 100,  44,  37,  62,  80,  93,  21,   7,  18,
        20,   6,  13,   7,   0,  71,  55,  36,  77,   0,  65])

In [49]:
np.random.randint(0,50,(15,3))

array([[38, 39, 23],
       [41,  8, 29],
       [26, 39,  3],
       [38, 42,  1],
       [30, 34, 49],
       [43, 31, 28],
       [27, 29, 47],
       [ 1, 48,  2],
       [32, 27, 30],
       [18,  8, 28],
       [44, 30, 33],
       [ 7, 11, 26],
       [ 5, 47, 36],
       [41,  8, 42],
       [44, 25,  8]])

In [51]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [52]:
arr=np.arange(0,25)

In [56]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
ranarr=np.random.randint(0,101,10)

In [58]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [59]:
ranarr.max()

99

In [61]:
ranarr.min()

2

In [62]:
ranarr.argmax()

5

In [63]:
ranarr.argmin()

7

In [64]:
ranarr.dtype

dtype('int32')

In [65]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [66]:
arr.shape

(25,)

In [67]:
arr=arr.reshape(5,5)

In [68]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [69]:
arr.shape

(5, 5)

In [70]:
arr=np.arange(0,11)

In [71]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
arr[8]

8

In [73]:
arr[1:5]

array([1, 2, 3, 4])

In [74]:
arr[:5]

array([0, 1, 2, 3, 4])

In [75]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [76]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
arr[0:5]=100

In [78]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [79]:
arr=np.arange(0,11)

In [80]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
sliced_arr=arr[5:]

In [83]:
sliced_arr[:]=99

In [84]:
sliced_arr

array([99, 99, 99, 99, 99, 99])

In [85]:
arr

array([ 0,  1,  2,  3,  4, 99, 99, 99, 99, 99, 99])

In [86]:
arr_copy=arr.copy()

In [87]:
arr_copy[:]=100

In [88]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [89]:
arr

array([ 0,  1,  2,  3,  4, 99, 99, 99, 99, 99, 99])

In [90]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [91]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [93]:
arr_2d.shape

(3, 3)

In [94]:
arr_2d[0]

array([ 5, 10, 15])

In [95]:
arr_2d[2]

array([35, 40, 45])

In [96]:
arr_2d[1,1]

25

In [97]:
arr_2d[1][1]

25

In [98]:
arr_2d[0,2]

15

In [99]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [100]:
arr=np.arange(1,11)

In [101]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [102]:
bool_arr=arr>4

In [103]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [104]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [105]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [106]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
arr=np.arange(0,10)

In [108]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [110]:
arr-2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [111]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [112]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [113]:
arr/arr

C:\Users\pkana\AppData\Local\Temp/ipykernel_12760/1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [114]:
1/arr

C:\Users\pkana\AppData\Local\Temp/ipykernel_12760/255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [115]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [116]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [117]:
np.log(arr)

C:\Users\pkana\AppData\Local\Temp/ipykernel_12760/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [118]:
arr.sum()

45

In [119]:
arr.mean()

4.5

In [120]:
arr.max()

9

In [121]:
arr.min()

0

In [122]:
arr.var()

8.25

In [124]:
arr.std()

2.8722813232690143

In [127]:
arr2d=np.arange(0,25).reshape(5,5)

In [130]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [128]:
arr2d.sum()

300

In [129]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [132]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])